### ISSUE TITLE
모든 테이블의 Auto Increment ID를 BIGINT 형으로 변경

### ISSUE THREAD

**Issue by berry2971** [orderoutofchaos/kry-judge#15]
김영한님의 강의를 참고하면, 대부분의 경우 Auto Increment를 통해 입력되는 ID 컬럼의 경우 데이터 타입을 BIGINT 형으로 한다고 합니다.

**Comment by gwanryo** [comment]
In [MariaDB documentation](https://mariadb.com/kb/en/auto_increment/),
> SERIAL is an alias for BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE.

I understand this statement says BIGINT UNSIGNED is recommended as column of AUTO_INCREMENT.
Updated SQL is available in discord channel.
