### ISSUE TITLE
디렉토리 rule 확립 필요성

### ISSUE THREAD

**Issue by jerry901** [orderoutofchaos/kry-judge#22]
이런 식으로 했으면 하는데 어떻게 생각하시는지 코멘트 부탁드립니다. 아래 예시는 하위 컨트롤러를 포함하는 모듈의 경로 예시입니다.

- /user
  - /controller
    - userController.kt
  - /entity
    - User.kt
  - /service
    - userService.kt
  -  /permission
     - /controller
       - permissionController.kt
     - /entity
       - permission.kt
     -  /service
        - permissionService.kt

**Comment by gwanryo** [comment]
LTGM, but it should be applied to all directory

**Comment by gwanryo** [comment]
제가 걱정하는건 url이 2차, 3차, 4차, ... 로 들어가면 구조가 복잡해지지 않을까? 하는 부분입니다

**Comment by jerry901** [comment]
네 이 방법이 아니라면 다른 방법으로라도 일단 중요한건 통일이니까..   방법을 의논해 보아야할 것 같습니다...

**Comment by berry2971** [comment]
일단, domain이라고 안 하고 entity라고 할지 궁금합니다.

**Comment by berry2971** [comment]
나머지는 저는 좋네요

**Comment by dsyun96** [comment]
퍼미션이 유저랑 동등한 레벨에 있으면 문제될 부분이 있을까요?

**Comment by dsyun96** [comment]
좋아보입니다.

**Comment by gwanryo** [comment]
해당 rule대로 확인하도록 하겠습니다.
