### ISSUE TITLE
API를 위한 URL 분리

### ISSUE THREAD

**Issue by berry2971** [orderoutofchaos/kry-judge#24]
API 호출을 위해서 사용되는 경우 최상단, 또는 적절한 위치에 api가 붙어야 할 것 같습니다. 예를 들어, '공지사항' 게시판에 접속하고자 하는 user는 .../board/notice를 적절한 URL이라 생각할 것입니다. 이는 곧 JSON을 반환하는 API가 아니라, 어떤 뷰(V)로 연결되어야 할 것임을 의미하며, 오히려 해당 뷰(V) 구현에 .../api/board/notice와 같은 격리된 API 호출이 사용되어야 할 것임을 의미합니다.
틀린 부분이 있으면 지적해주시고, 또는 다른 생각이나 구체적인 구현 방안도 제시해주세용!

**Comment by gwanryo** [comment]
> 배포할때 프론트랑 서버는 각각 도커 컨테이너로 독립된 환경에서 동작하도록 배포하는게 좋을것 같고, 프론트가 /api/... 주소로 요청을 보내면 중간에 nginx가 받아서 /api/로 시작한 애들은 앞에 /api 떼고 백엔드 컨테이너로 포워딩 해주는 식으로 처리하면 됨

@blurfx 님 답변입니다.
독립된 환경에서 돌아간다는걸 생각을 못했네요.

제 생각에는 굳이 앞쪽에 `/api` 를 추가하지 않아도 될 것 같습니다.

**Comment by berry2971** [comment]
> > 배포할때 프론트랑 서버는 각각 도커 컨테이너로 독립된 환경에서 동작하도록 배포하는게 좋을것 같고, 프론트가 /api/... 주소로 요청을 보내면 중간에 nginx가 받아서 /api/로 시작한 애들은 앞에 /api 떼고 백엔드 컨테이너로 포워딩 해주는 식으로 처리하면 됨
> 
> @blurfx 님 답변입니다.
> 독립된 환경에서 돌아간다는걸 생각을 못했네요.
> 
> 제 생각에는 굳이 앞쪽에 `/api` 를 추가하지 않아도 될 것 같습니다.

구웃
