### ISSUE TITLE
Change column type DATETIME to TIMESTAMP

### ISSUE THREAD

**Issue by gwanryo** [orderoutofchaos/kry-judge#28]
# 문제
잘못된 type 사용으로 인한 timezone 처리의 복잡성 증가

# 해결 방안
`DATETIME` 열을 모두 `TIMESTAMP`로 변경

# 영향 범위
`DATETIME` 자료형이 포함된 모든 TABLE

**Comment by gwanryo** [comment]
이견이 있으시다면 코멘트로 이야기해주세요.

**Comment by dsyun96** [comment]
timestamp를 쓰되 time zone이랑 같이 쓸 수 있는 건가요?
저번에 톡방에서 좀 얘기하다가 결국 [time zone 없이는 timestamp를 쓰지 말라](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29)고 결론 난 것 같아서요.

**Comment by gwanryo** [comment]
> timestamp를 쓰되 time zone이랑 같이 쓸 수 있는 건가요? (잘 모름)
> 저번에 톡방에서 좀 얘기하다가 결국 [time zone 없이는 timestamp를 쓰지 말라](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29)고 결론 난 것 같아서요.

아무래도 해외에서 사용한다고 가정했을 때, 프론트 단에서 브라우저의 timezone을 가져와서 변환하는게 괜찮지 않을까 생각합니다.
백 단에서 timezone을 어떻게 바꿀 수 있을까 생각을 해봤는데 제가 아는 지식으로는 복잡한 방법 밖에 안떠오르네요.

**Comment by gwanryo** [comment]
좀 더 고민해야 할 [글](https://nesoy.github.io/articles/2020-02/mysql-datetime-timestamp)이 보이네요.

MySQL의 경우에는 `DATETIME`이 `timezone`에 독립적이라고 합니다.
`TIMESTAMP`가 오히려 `timezone`을 바꾸면 바뀌네요.

가능하시면 확인 부탁드려도 되겠습니까?

**Comment by gwanryo** [comment]
@dsyun96 혹시 추가할 의견 없으시면 `DATETIME` 사용하도록 하겠습니다.
#39 에서 `DATETIME(6)` 사용하시는 것 확인하여, 일단 Close합니다.
