### ISSUE TITLE
권한 테이블 구조적 의문점

### ISSUE THREAD

**Issue by jerry901** [orderoutofchaos/kry-judge#29]
# 의문점
 Entity를 작성하다 보니 USER 테이블과 PERMGROUP 테이블, 그리고 USER_PERMGROUP 테이블만 있으면 권한 관리는 구현할 수 있을 것 같다는 생각이 드네요. 

> 아래는 spring security의 짧은 구현 예제 입니다. 
url 매핑에 대해 해당 유저가 그룹에 속해 있는지만 체크하기 때문에 세부적인 권한 하나하나 까지는 다루지 않는 방향이 어떨지 합니다.
```java
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
           .authorizeRequests()
           .antMatchers("/").permitAll()
           .antMatchers("/user").hasRole("USER")
           .antMatchers("/manager").hasRole("MANAGER")
           .antMatchers("/admin").hasRole("ADMIN")
           .anyRequest().authenticated()
       .and()
           .formLogin();
    }
```

물론 저도 확신을 가진 것은 아니기 때문에 짧은 의견 한줄 씩 부탁드리겠습니다...

**Comment by gwanryo** [comment]
네, 말씀하신 부분이 맞습니다.
역할을 지정하고, 그 역할이 있는지만 확인하면 간단하게 `antMatchers`로 구현이 가능합니다.
굳이 테이블을 `PERMISSION`과 `PERMGROUP`으로 나눌 필요도 없습니다.

해당 이슈에서 저는 두 가지를 말씀드리고 싶습니다.
1. `PERMGROUP`과 `PERMISSION`을 나눈 이유
2. `antMatchers` 말고 [`@PreAuthorize`](https://www.baeldung.com/spring-security-check-user-role)를 사용하자

이를 설명하기 위해서 `board` 기능을 예시로 들어보겠습니다.

* 게시글을 읽고 (`GET /board/{boardName}/article/{articleId}`)
* 게시글을 작성하고 (`POST /board/{boardName}`)
* 게시글을 수정하고 (`PUT /board/{boardName}/article/{articleId}`)
* 게시글을 삭제하는 (`DELETE /board/{boardName}/article/{articleId}`)

위와 같은 기능이 있다고 했을 때, 생각하고 계신 권한대로 나누자면 아래와 같을 것입니다.

* READ는 `guest`부터
* WRITE는 `user`부터
* MODIFY는 `admin` 혹은 `user` 본인
* DELETE는 `admin` 혹은 `user` 본인

이 상황에서 갑자기 **게시판 삭제만 가능한** `moderator`를 추가하고 싶다고 가정해봅시다.

> `moderator`를 `PERMGROUP`에 추가하고,
`moderator`를 `antMatchers`에 등록하고, ..., 어?

불가피하게 소스코드의 수정이 일어날 수 밖에 없습니다.
굉장히 귀찮지요.

저는 이런 상황을 피하기 위해서 `소스 코드에서 결정하는 Role (READ, WRITE, ...)`과 `실제 Role (user, admin, ...)`을 분리하는 것이 좋다고 생각하였습니다.
이는 `소스 코드에서 결정하는 Role`은 각각 메서드에서 모두 다르게 설정할 수 있다는 점을 이용한다면 충분히 가능합니다.

`소스 코드에서 결정하는 Role`은 `PERMISSION`으로, 해당 `PERMISSION`들을 다수 가진 `실제 Role`을 `PERMGROUP`으로 생각해봅시다.

* `GET /board/{boardName}/article/{articleId}`를 `PERM_READ_ARTICLE`
* `POST /board/{boardName}`를 `PERM_WRITE_ARTICLE`
* `PUT /board/{boardName}/article/{articleId}`)를 `PERM_MODIFY_ARTICLE`
* `DELETE /board/{boardName}/article/{articleId}`)를 `PERM_DELETE_ARTICLE`

이런 식으로 메서드들의 권한을 모두 쪼개어서 소스 코드를 작성합니다. 그리고, 이를 `PERMISSION`으로 등록합니다.
이러한 `PERMISSION`들은 `guest`, `user`, `admin` 등의 `PERMGROUP`으로 묶어서 관리됩니다.

`guest`는 `PERM_READ_ARTICLE`만 가지고 있고,
`user`는 `PERM_READ_ARTICLE`, `PERM_WRTIE_ARTICLE`를 가지고 있고, ...

이렇게 말입니다.
해당 상황에서 만약 `moderator`에 대한 새로운 추가 요구가 들어온다고 해봅시다.

> `PERMISSION`에는 이미 `PERM_DELETE_ARTICLE`이 존재하고,
`PERMGROUP`에 `moderator`를 추가하고,
`PERMISSION_PERMGROUP`에 `PERM_DELETE_ARTICLE, moderator`를 추가하자!

위 과정에서 소스 코드를 수정할 필요가 없어졌습니다.
깔끔하게 요구사항에 대응할 수 있는 것이지요.

제가 굳이 `PERMISSION`과 `PERMGROUP`를 분리한 이유는 위와 같이 분리했을 때 생기는 이점을 생각했기 때문입니다.

**`antMatchers` 대신에 [`@PreAuthorize`](https://www.baeldung.com/spring-security-check-user-role)를 사용하자**도 비슷한 맥락에서 시작합니다.
[`@PreAuthorize`](https://www.baeldung.com/spring-security-check-user-role)는 위 상황에서 알맞게 사용할 수 있고, `antMatchers`에 비해서 메서드가 어떤 권한인지 보기가 쉽고, 기능 추가/유지보수에서 권한을 조절하기도 쉬워지기 때문입니다.

이상이 제 의견입니다.
추가적인 건의나 문제점, 개선점은 언제든지 의견 부탁드립니다.

**Comment by jerry901** [comment]
알겠습니다 그러면 설계대로 진행하겠습니다.

**Comment by gwanryo** [comment]
감사합니다.
